### ISSUE TITLE
support for visual studio code

### ISSUE THREAD

**Issue by RJmsG** [Minecraft-GoodTime/GoodTime-Java-Minecraft-Launcher-Core#1]
Hi, I'm using visual studio code, and I don't know what I should do.
I see that you mentioned itellij idea, but does it work for anything else?

**Comment by BestOwl** [comment]
This project uses Gradle build system, so you can install the *Gradle for Java* vscode extension, and then import the project

**Comment by RJmsG** [comment]
Thanks!
